# Generated by Django 2.2.16 on 2022-06-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220616_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Тип произведения', 'verbose_name_plural': 'Тип произведений'},
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
