# Generated by Django 2.2.16 on 2022-06-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220621_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
